[package]
name = "verifier-p256"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ckb-std.workspace = true
ckb-account-protocol = { path = "../../crates/protocol", default-features = false }
p256.workspace = true
sha2.workspace = true
ckb-hash = { workspace = true, default-features = false, features = ["ckb-contract"] }
